### ISSUE TITLE
[Feat] MealDetail UI 업데이트

### ISSUE THREAD

**Issue by eunbkang** [Bnomad-space/IAteIt#14]
### 작업할 내용

- 한 끼니 포스팅당 하나의 장소를 입력하도록 장소/시간 표시 UI를 수정합니다.
- text로 되어 있던 캡션/장소 입력칸을 값이 있으면 표시하고 없으면 textfield와 입력창이 나오도록 수정합니다.
- 사진 카드 위의 사진 추가 버튼을 없애고 맨 마지막 사진에서 pull to add 되도록 합니다.

### 스크린샷 혹은 gif

<p list="left">
<img width="280" alt="Screen Shot 2023-03-08 at 11 28 56 PM" src="https://user-images.githubusercontent.com/103012157/223739475-db2acff4-525d-4dfd-a9b4-2f0919759aa3.png">
<img width="280" alt="Screen Shot 2023-03-08 at 11 29 10 PM" src="https://user-images.githubusercontent.com/103012157/223739548-96516057-b592-4d3f-83dd-e3872a0b4f30.png">
</p>

### TODO

- [x] 장소/시간 표시 UI 수정
- [ ] 캡션, 장소 입력창 및 done 버튼 추가
- [ ] 사진추가 pull to add로 구현
