### ISSUE TITLE
[Feat] 카메라 셔터 효과, 핀치 줌 ui 적용

### ISSUE THREAD

**Issue by Willowwryu** [Bnomad-space/IAteIt#19]
### 작업할 내용

- 카메라 셔터 버튼 누를시 촬영되었다는 피드백을 주기 위해 깜빡임 효과 적용
- 제스터를 통한 핀치 줌 기능 구현
- 상단바 문구, 취소버튼 구현 
- 촬영후 확인 화면 ui구현

### TODO

- [x] 셔터 피드백 추가
- [ ] 핀치줌 구현
- [x] 상단바 문구
- [x] 카메라 닫기버튼
- [x] 촬영 후 확인 화면 구현
- [x] 리테이크, 업로드 버튼 구현

**Comment by heokyeol** [comment]
태그부탁드림다

**Comment by Willowwryu** [comment]
핀치 줌 기능은 팀원과 회의 후 추가 여부 결정
