### ISSUE TITLE
[Feat] 신규 데이터 구조 기반 Mock Data 생성

### ISSUE THREAD

**Issue by hardworking-nomad** [Bnomad-space/IAteIt#24]
### 작업할 내용

- 다수의 Meal, Plate 생성 (프로필 뷰에서 모아볼 수 있도록 일자별 다양한 데이터 생성)
- ChatGPT 활용하여 데이터 구조 학습시키고 Mock Data 자동으로 생성할 수 있을지 검토

### 스크린샷 혹은 gif

<img width="800" alt="image" src="https://user-images.githubusercontent.com/103012800/228211899-9887e3e5-cb17-409e-9a7d-6e23c92606c1.png">

### TODO

- [ ] ChatGPT 에 데이터 구조 학습 및 Extension 형태로 MockData 생성 가능한지 실험
- [ ] 자동 생성 가능할 시 다수 데이터 입력
- [ ] 자동 불가능할 시 수기로 데이터 입력
