### ISSUE TITLE
[Feat] MyProfileView 생성

### ISSUE THREAD

**Issue by hardworking-nomad** [Bnomad-space/IAteIt#3]
### 작업할 내용

프로필뷰를 생성하고 프로필사진과 내가 먹은 끼니들의 히스토리를 확인하는 뷰를 만듭니다.

### 스크린샷 혹은 gif

<img width="224" alt="image" src="https://user-images.githubusercontent.com/103012800/220843054-0f7636ba-f177-40e3-aaed-8809c41e116a.png">

### TODO

- [ ] 프로필 사진 삽입
- [ ] 날짜별 끼니 테이블 뷰 생성
- [ ] 캘린더 버튼 (혹은 설정 버튼?) 더미 삽입
