### ISSUE TITLE
[Feat] MealDetailView - Meal에 Plate, 캡션, 장소 추가 기능

### ISSUE THREAD

**Issue by eunbkang** [Bnomad-space/IAteIt#44]
### 작업할 내용

MealDetailView의 Comment를 제외한 나머지 기능을 구현합니다.
- Add a plate 버튼과 기능을 추가합니다.
- 캡션과 장소를 입력하여 저장할 수 있도록 합니다.

### TODO

- [x] Add a plate 버튼 UI 만들기
- [x] addPlateToMeal 함수 연결
- [x] 캡션 저장 기능 구현
- [x] 장소 저장 기능 구현
