### ISSUE TITLE
[Feat] Profile View 안의 Meal History View 리팩토링

### ISSUE THREAD

**Issue by hardworking-nomad** [Bnomad-space/IAteIt#52]
### 작업할 내용

내가 먹은 Meal의 히스토리를 리팩토링합니다.
List 를 가로, 세로 스크롤뷰의 조합으로 바꾸고, 한 날짜에 모여있는 Meal들을 각각의 Card 혹은 Tile 형태로 표시하도록 수정합니다.

### 관련 이슈넘버

#31

### TODO

- [ ] List 의 Row 대신 Scroll View 의 Row 로 수정하고, 하나의 Row 를 구성하는 각각의 Tile / Card 를 클릭 가능하도록 수정
- [ ] Tile/Card, Row 를 Component 화
- [ ] 프로필 영역은 고정하고 하단의 Meal History 만 스크롤 되도록 수정
