### ISSUE TITLE
[Feat] plate, meal 삭제 기능

### ISSUE THREAD

**Issue by eunbkang** [Bnomad-space/IAteIt#58]
### 작업할 내용

- meal 내 개별 plate 삭제 기능, meal 전체 삭제 기능을 만듭니다.
- plate 삭제는 해당 plate를 길게 눌렀을 때 나오는 contextMenu를 이용하고, meal 삭제는 네비게이션바 우상단 버튼을 이용하려고 합니다.

### TODO

- [x] plate 삭제 UI
- [x] meal 삭제 UI
- [x] plate 삭제 기능
- [x] meal 삭제 기능
