### ISSUE TITLE
[Feat] CameraView UI 수정, 카메라 촬영 저장기능 구현

### ISSUE THREAD

**Issue by Willowwryu** [Bnomad-space/IAteIt#8]
### 작업할 내용

- 지난 회의에서 셔터버튼 외에 버튼없애기로 결정 반영하기
- 셔터버튼 촬영, 저장기능 구현

### TODO

- [x] 플래시, 전후면 변경 버튼 제거
- [x] 셔터버튼 촬영 기능
- [x] 셔터버튼 촬영 후 저장 기능
